### ISSUE TITLE
Is it work on Windows 7 OS ?

### ISSUE THREAD

**Issue by jespa007** [visualcamp/seeso-sample-windows#6]
I wonder why windows 10 OS is required... Is there anything that will not work in windows 7 ?

**Comment by leeyongeun9** [comment]
Sorry about being late. This was the first issue that we got from the public. 🤕 

For the question, we only have tested the sample on Windows 10 yet.
We will test it on Windows 7 in June,
there probably has no problem with Windows 7 but we cannot confirm.

Thank you!

**Comment by leeyongeun9** [comment]
@jespa007  We finished testing in Windows7
The SDK works well in Windows7.

**Comment by jespa007** [comment]
@YongEun-vc  thanks to test it out :+1:
